version: "2.3"
services:
  backend-demo-postgres:
    image: registry.app.corpintra.net/dockerhub/library/postgres:13.4
    container_name: backend-demo-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "backend-demo"
    ports:
      - "5431:5432"
