
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/backend-demo
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog.root.xml
    enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
