name: ci pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Dependabot Checkout
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request_target'
        with:
          # Dependabot can only check out at the HEAD of the PR branch
          ref: ${{ github.event.pull_request.head.sha }}

      - name: yarn install
        run: yarn install
